### ISSUE TITLE
404 in http://perl6.org/community/

### ISSUE THREAD

**Issue by zoffixznet** [Raku/raku.org#130]
On http://perl6.org/community/ in 

> Internet Relay Chat (IRC)
> Much discussion happens on #perl6, our IRC channel. This is the fastest way to get help.

The link to `#perl6` is a 404

**Comment by AlexDaniel** [comment]
On a related note, [according to undersightable](https://gist.github.com/0d7e7a0a8a74722aee1451385661f7bb), there's also a problem with https://irc.perl6.org.

@timo by any chance do you know if there's a main ticket somewhere for issues related to infrastructure resurrection? I know there's https://github.com/perl6/problem-solving/issues/9 but I think @rba and @maettu are working on more important issues (i.e. how to make sure it doesn't happen again, instead of fixing some broken links one by one).

**Comment by timo** [comment]
i've just fixed the irc one and the rosettacode link (because it's in the same directory) but somehow this must previously have worked the way the source is laid out here :|

also, surely more links are broken, who wants to hunt for them while i have dinner?

**Comment by lukasvalle** [comment]
There is also an other ticket about the broken links: https://github.com/perl6/perl6.org/issues/127

**Comment by rba** [comment]
looks fixed. keep it for myself to be able to double-check after hosting is moved to a permanent solution.

**Comment by 2colours** [comment]
@rba can this issue be closed? :)
